# Standard Sequential Models

## (1): Setup

In [5]:
import tensorflow as tf
import keras
from keras import layers

## (2): When the Use Sequential Models

In [22]:
seq_model_1 = keras.Sequential(
    [
        layers.Dense(2, activation = 'relu', name = 'layer1'),
        layers.Dense(2, activation = 'relu', name = 'layer2'),
        layers.Dense(2, activation = 'linear', name = 'layer3'),
    ]
)

# array of Dense layers

In [23]:
ones_tensor = tf.ones((3, 3))

In [24]:
ones_tensor

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [25]:
seq_model_1(ones_tensor)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.24795596, -0.25923353],
       [-0.24795596, -0.25923353],
       [-0.24795596, -0.25923353]], dtype=float32)>

How does it make sense? The input is `(3, 3)`, but the first layer has 2 nodes.

In [26]:
ones_tensor_2 = tf.ones(
    shape = (4, 4)
)

In [27]:
seq_model_1(ones_tensor_2)

ValueError: Exception encountered when calling Sequential.call().

Input 0 of layer "layer1" is incompatible with the layer: expected axis -1 of input shape to have value 3, but received input with shape (4, 4)

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=(4, 4), dtype=float32)
  • training=None
  • mask=None
  • kwargs=<class 'inspect._empty'>

It does care about shape somehow... I guess that `2` doesn't mean number of nodes or something...

## (3): Creating Seequential Models

In [29]:
seq_model_2 = keras.Sequential(
    [
        layers.Dense(5, activation = "relu", use_bias = False),
        layers.Dense(1, activation = "relu", use_bias = False)
    ]
)

In [30]:
seq_model_2.layers

[<Dense name=dense_1, built=False>, <Dense name=dense_2, built=False>]

In [31]:
type(seq_model_2.layers)

list

In [32]:
seq_model_2.add(layers.Dense(2, activation = 'relu'))
seq_model_2.add(layers.Dense(1, activation = 'relu'))

In [33]:
seq_model_2.layers

[<Dense name=dense_1, built=False>,
 <Dense name=dense_2, built=False>,
 <Dense name=dense_3, built=False>,
 <Dense name=dense_4, built=False>]

## (4): Input Shape

In [34]:
layer_1 = layers.Dense(3)

In [36]:
layer_1.weights

[]

Doesn't know kernel dimension because unsure of the input dimension.

In [37]:
ones_tensor

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [38]:
ones_tensor_2

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [39]:
layer_1(ones_tensor)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-1.0275948 ,  1.3545821 ,  0.00739193],
       [-1.0275948 ,  1.3545821 ,  0.00739193],
       [-1.0275948 ,  1.3545821 ,  0.00739193]], dtype=float32)>

In [40]:
layer_1(ones_tensor_2)

ValueError: Input 0 of layer "dense_5" is incompatible with the layer: expected axis -1 of input shape to have value 3, but received input with shape (4, 4)

Alright... Slowly understanding..

In [42]:
ones_tensor_3 = tf.ones(
    shape = (1, 4) # one row, four columns
)

In [43]:
ones_tensor_3

<tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[1., 1., 1., 1.]], dtype=float32)>

In [44]:
ones_tensor_3.shape

TensorShape([1, 4])

In [45]:
layer_1(ones_tensor_3)

ValueError: Input 0 of layer "dense_5" is incompatible with the layer: expected axis -1 of input shape to have value 3, but received input with shape (1, 4)

Probably has initialized its input dimension from previous usage.

In [50]:
layer_2 = layers.Dense(5)

In [51]:
layer_2(ones_tensor_3)

<tf.Tensor: shape=(1, 5), dtype=float32, numpy=
array([[ 0.80898726,  0.89339256,  0.43492913, -1.2216899 ,  0.33896148]],
      dtype=float32)>

(1, 4) to (1, 5)... (x, p) to (x, q)?

In [54]:
layer_3 = layers.Dense(6)

In [55]:
ones_tensor_4 = tf.ones(
    shape = (5, 10)
)

In [56]:
layer_3(ones_tensor_4)

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[ 0.0364747 , -1.0383513 ,  0.88842523, -0.60200775,  1.1545554 ,
        -1.7219542 ],
       [ 0.0364747 , -1.0383513 ,  0.88842523, -0.60200775,  1.1545554 ,
        -1.7219542 ],
       [ 0.0364747 , -1.0383513 ,  0.88842523, -0.60200775,  1.1545554 ,
        -1.7219542 ],
       [ 0.0364747 , -1.0383513 ,  0.88842523, -0.60200775,  1.1545554 ,
        -1.7219542 ],
       [ 0.0364747 , -1.0383513 ,  0.88842523, -0.60200775,  1.1545554 ,
        -1.7219542 ]], dtype=float32)>

(5, 10) to (5, 6). Yes. "Batch dimension" preserved.

In [68]:
seq_model_3 = keras.Sequential(
    [
        keras.layers.Dense(2, activation = "relu"),
        keras.layers.Dense(3, activation = "relu"),
        keras.layers.Dense(2, activation = "relu"),
        keras.layers.Dense(1, activation = "linear"),
    ]
)

In [58]:
seq_model_3.weights

[]

In [63]:
random_tensor_1 = tf.random.uniform(
    shape = (50, 1),
    maxval = 5.0,
    minval = -5.0
)

# sample x between [-5, 5] uniformly 50 times

In [64]:
random_tensor_1

<tf.Tensor: shape=(50, 1), dtype=float32, numpy=
array([[ 2.2534142 ],
       [-0.15424824],
       [-1.0282767 ],
       [-3.2357836 ],
       [-1.2513471 ],
       [ 4.520541  ],
       [ 1.0766735 ],
       [-0.7187295 ],
       [ 3.6800337 ],
       [-2.1762753 ],
       [ 2.6204262 ],
       [-2.7330685 ],
       [-2.3565018 ],
       [ 2.7350712 ],
       [ 2.9006777 ],
       [ 2.7819228 ],
       [-4.445854  ],
       [-2.0915031 ],
       [-4.078412  ],
       [ 4.867428  ],
       [ 0.05807495],
       [-1.4666271 ],
       [ 3.6749039 ],
       [ 3.798852  ],
       [ 0.47329426],
       [-3.7814248 ],
       [-0.14174366],
       [-3.6979628 ],
       [-2.1776116 ],
       [-3.6635733 ],
       [ 1.7778611 ],
       [-0.45158768],
       [-1.7247009 ],
       [ 3.4241915 ],
       [ 4.6210146 ],
       [-3.2847512 ],
       [ 0.03328419],
       [ 0.10878563],
       [ 1.9151249 ],
       [ 1.4948597 ],
       [-1.4094043 ],
       [ 0.12163258],
       [ 4.1529045 ],
     

In [69]:
seq_model_3(random_tensor_1)

<tf.Tensor: shape=(50, 1), dtype=float32, numpy=
array([[-0.5596568 ],
       [-0.05418495],
       [-0.3612173 ],
       [-1.1366794 ],
       [-0.43957838],
       [-1.1227194 ],
       [-0.2674021 ],
       [-0.25247827],
       [-0.91397136],
       [-0.764491  ],
       [-0.6508078 ],
       [-0.9600836 ],
       [-0.8278017 ],
       [-0.679281  ],
       [-0.72041094],
       [-0.6909171 ],
       [-1.5617579 ],
       [-0.7347119 ],
       [-1.4326816 ],
       [-1.208872  ],
       [-0.01442347],
       [-0.5152028 ],
       [-0.9126973 ],
       [-0.9434811 ],
       [-0.11754713],
       [-1.3283545 ],
       [-0.0497923 ],
       [-1.2990357 ],
       [-0.76496047],
       [-1.2869551 ],
       [-0.44154873],
       [-0.15863559],
       [-0.60586005],
       [-0.85043055],
       [-1.147673  ],
       [-1.153881  ],
       [-0.00826645],
       [-0.02701795],
       [-0.47563946],
       [-0.37126264],
       [-0.49510136],
       [-0.03020861],
       [-1.0314133 ],
     

In [70]:
seq_model_3.weights

[<Variable path=sequential_8/dense_15/kernel, shape=(1, 2), dtype=float32, value=[[ 0.37395477 -0.40826738]]>,
 <Variable path=sequential_8/dense_15/bias, shape=(2,), dtype=float32, value=[0. 0.]>,
 <Variable path=sequential_8/dense_16/kernel, shape=(2, 3), dtype=float32, value=[[-0.8883432   0.38076806  0.6175126 ]
  [-0.8892931  -1.0512011   0.6859567 ]]>,
 <Variable path=sequential_8/dense_16/bias, shape=(3,), dtype=float32, value=[0. 0. 0.]>,
 <Variable path=sequential_8/dense_17/kernel, shape=(3, 2), dtype=float32, value=[[-0.69568133 -0.9913102 ]
  [-0.851516   -0.22413367]
  [-0.85093516  0.9693804 ]]>,
 <Variable path=sequential_8/dense_17/bias, shape=(2,), dtype=float32, value=[0. 0.]>,
 <Variable path=sequential_8/dense_18/kernel, shape=(2, 1), dtype=float32, value=[[-0.15869236]
  [-1.2939662 ]]>,
 <Variable path=sequential_8/dense_18/bias, shape=(1,), dtype=float32, value=[0.]>]

Should have... $2 \times 3 + 3 \times 2 + 2$ weights? $14$ total?

In [75]:
seq_model_3.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_15 (Dense)                │ (50, 2)                │             4 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_16 (Dense)                │ (50, 3)                │             9 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_17 (Dense)                │ (50, 2)                │             8 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_18 (Dense)                │ (50, 1)                │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 24 (96.00 B)

 Trainable params: 24 (96.00 B)

 Non-trainable params: 0 (0.00 B)

Huh... Oh, we forgot biases.

First to second: $2 \times 3 + 3 = 9$.
Second to third: $3 \times 2 + 2 = 8$.
Third to fourth: $2 \times 1 + 1 = 3$.

Alright, but there are still four parameters in going from the input data to the first two nodes... I see two biases for each, but... I don't see where the other two come from. I can't picture the weight kernel if there is one.

In [76]:
seq_model_3.layers

[<Dense name=dense_15, built=True>,
 <Dense name=dense_16, built=True>,
 <Dense name=dense_17, built=True>,
 <Dense name=dense_18, built=True>]

## (5): Workflow Debugging

In [87]:
new_model = keras.Sequential()

In [88]:
new_model.add(keras.Input(shape = (250, 250, 3)))

In [89]:
new_model.add(layers.Conv2D(32, 5, strides = 2, activation = 'relu'))

In [90]:
new_model.add(layers.Conv2D(32, 3, activation = 'relu'))

In [91]:
new_model.add(layers.MaxPooling2D(3))

In [92]:
new_model.summary()

Model: "sequential_11"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_5 (Conv2D)               │ (None, 123, 123, 32)   │         2,432 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_6 (Conv2D)               │ (None, 121, 121, 32)   │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 40, 40, 32)     │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 11,680 (45.62 KB)

 Trainable params: 11,680 (45.62 KB)

 Non-trainable params: 0 (0.00 B)

In [93]:
new_model.add(layers.Conv2D(32, 3, activation = 'relu'))
new_model.add(layers.Conv2D(32, 3, activation = 'relu'))
new_model.add(layers.MaxPooling2D(3))
new_model.add(layers.Conv2D(32, 3, activation = 'relu'))
new_model.add(layers.Conv2D(32, 3, activation = 'relu'))
new_model.add(layers.MaxPooling2D(2))

In [94]:
new_model.summary()

Model: "sequential_11"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_5 (Conv2D)               │ (None, 123, 123, 32)   │         2,432 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_6 (Conv2D)               │ (None, 121, 121, 32)   │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 40, 40, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_7 (Conv2D)               │ (None, 38, 38, 32)     │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_8 (Conv2D)               │ (None, 36, 36, 32)     │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 12, 12, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_9 (Conv2D)               │ (None, 10, 10, 32)     │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_10 (Conv2D)              │ (None, 8, 8, 32)       │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_3 (MaxPooling2D)  │ (None, 4, 4, 32)       │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 48,672 (190.12 KB)

 Trainable params: 48,672 (190.12 KB)

 Non-trainable params: 0 (0.00 B)

In [95]:
new_model.add(layers.GlobalMaxPool2D())

In [96]:
new_model.add(layers.Dense(10))

In [97]:
new_model.summary()

Model: "sequential_11"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_5 (Conv2D)               │ (None, 123, 123, 32)   │         2,432 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_6 (Conv2D)               │ (None, 121, 121, 32)   │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 40, 40, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_7 (Conv2D)               │ (None, 38, 38, 32)     │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_8 (Conv2D)               │ (None, 36, 36, 32)     │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 12, 12, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_9 (Conv2D)               │ (None, 10, 10, 32)     │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_10 (Conv2D)              │ (None, 8, 8, 32)       │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_3 (MaxPooling2D)  │ (None, 4, 4, 32)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_max_pooling2d            │ (None, 32)             │             0 │
│ (GlobalMaxPooling2D)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_19 (Dense)                │ (None, 10)             │           330 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 49,002 (191.41 KB)

 Trainable params: 49,002 (191.41 KB)

 Non-trainable params: 0 (0.00 B)

## (6): Feature Extraction

Layers have input and output attributes.

In [99]:
cool_layer = layers.Dense(4)

In [100]:
cool_layer.input

AttributeError: The layer dense_21 has never been called and thus has no defined input.

I agree with that.

In [101]:
cool_layer.output

AttributeError: The layer dense_21 has never been called and thus has no defined output.

Oh. Even output is not defined?

In [102]:
initial_model = keras.Sequential(
    [
        keras.Input(shape = (250, 250, 3)),
        layers.Conv2D(32, 5, strides = 2, activation = 'relu'),
        layers.Conv2D(32, 3, activation = 'relu'),
        layers.Conv2D(32, 3, activation = 'relu'),
    ]
)

In [103]:
initial_model.inputs

[<KerasTensor shape=(None, 250, 250, 3), dtype=float32, sparse=False, ragged=False, name=keras_tensor_103>]

In [104]:
initial_model.layers

[<Conv2D name=conv2d_11, built=True>,
 <Conv2D name=conv2d_12, built=True>,
 <Conv2D name=conv2d_13, built=True>]

In [106]:
[layer.output for layer in initial_model.layers]

[<KerasTensor shape=(None, 123, 123, 32), dtype=float32, sparse=False, ragged=False, name=keras_tensor_104>,
 <KerasTensor shape=(None, 121, 121, 32), dtype=float32, sparse=False, ragged=False, name=keras_tensor_105>,
 <KerasTensor shape=(None, 119, 119, 32), dtype=float32, sparse=False, ragged=False, name=keras_tensor_106>]

In [111]:
feature_extractor = keras.Model(
    inputs = initial_model.inputs,
    outputs = [layer.output for layer in initial_model.layers]
)

# this one is not so well-explained...

So, this model actually has several different outputs... Is that right? Recall the top of the page about inappropriate uses of Sequential models:

> A Sequential model is not appropriate when:
> - Your model has multiple inputs or multiple outputs
> ...

Maybe that's what they mean.

In [112]:
images = tf.ones(
    shape = (1, 250, 250, 3)
)

In [113]:
features = feature_extractor(images)

In [115]:
len(features)

3

## (7): Transfer Learning

Ehh... Maybe hold off on this for now.