Following: https://docs.pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html

In [1]:
import torch

Can make Torch tensors just through standard Python `list` -> `torch.tensor` map.

In [2]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [3]:
string_data = torch.tensor("funny")

TypeError: new(): invalid data type 'str'

In [ ]:
string_data = torch.tensor(["funny"])

ValueError: too many dimensions 'str'

In [ ]:
string_array = [["cool", "warm"], ["hot", "cold"]]
temperature_tensor = torch.tensor(string_array)

ValueError: too many dimensions 'str'

Can make tensors from extant tensors. Sure.

In [4]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



And the familiar, basic initialization procedures:

In [5]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.8275, 0.8865, 0.6449],
        [0.2038, 0.7100, 0.6165]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


Tensor attributes are familiar.

In [6]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


> By default, tensors are created on the CPU.

Alright.

In [7]:
torch.accelerator.is_available()

True

In [8]:
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())

In [9]:
torch.accelerator.current_accelerator()

device(type='cuda')

Is there some property of the `tensor` that shows if it's on an accelerator?

In [10]:
tensor = torch.ones(4, 4)

print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [11]:
tensor[0, 0]

tensor(1.)

$T_{ij}$. So, $T_{i0}$ is the ith row and the 0th column. Will select out all elements of the 0th column.

In [12]:
tensor[0]

tensor([1., 1., 1., 1.])

In [13]:
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])


In [14]:
tensor[:,1] = 0

Does this assign $T_{i1} := 0$? Look for the $i$ th row and the $1$ st column to contain all $0$ s.

In [15]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

We can join tensors with concatenation.

In [16]:
t1 = torch.cat(
    [tensor, tensor, tensor], 
    dim = 1 # along the column-th dimension
)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


Note:

In [17]:
type([tensor, tensor, tensor])

list

If tensors are matrices (they aren't generally... this is a major misnomer), then we can do matrix operations.

In [18]:
random_matrix = torch.rand(5, 5)
random_matrix

tensor([[0.1255, 0.4977, 0.0669, 0.8651, 0.5732],
        [0.3256, 0.2884, 0.1859, 0.5840, 0.5724],
        [0.6712, 0.8564, 0.3158, 0.0837, 0.2637],
        [0.6060, 0.9718, 0.1016, 0.4387, 0.2144],
        [0.5937, 0.4321, 0.1661, 0.1651, 0.9286]])

In [19]:
random_matrix.T

tensor([[0.1255, 0.3256, 0.6712, 0.6060, 0.5937],
        [0.4977, 0.2884, 0.8564, 0.9718, 0.4321],
        [0.0669, 0.1859, 0.3158, 0.1016, 0.1661],
        [0.8651, 0.5840, 0.0837, 0.4387, 0.1651],
        [0.5732, 0.5724, 0.2637, 0.2144, 0.9286]])

In [20]:
random_matrix.inverse()

tensor([[-4.0674,  4.0523, -2.5299,  3.1032,  0.0149],
        [ 2.4020, -3.3490,  1.5209, -0.6843,  0.3077],
        [ 1.1387,  1.2426,  4.4465, -4.0740, -1.7912],
        [-0.6477,  2.3510, -1.0516,  0.9968, -0.9809],
        [ 1.3944, -1.6730,  0.3014, -1.1141,  1.4191]])

In [21]:
random_matrix.inverse () @ random_matrix

tensor([[ 1.0000e+00, -1.6604e-07,  1.0974e-09,  1.3929e-07,  2.7633e-07],
        [ 2.4793e-08,  1.0000e+00,  4.7230e-08,  1.0054e-08, -1.3427e-07],
        [-3.8609e-07, -9.7881e-08,  1.0000e+00, -2.0205e-07, -2.3935e-07],
        [-6.0245e-08, -2.0202e-07, -3.4010e-08,  1.0000e+00,  1.1594e-07],
        [ 2.9516e-07,  5.0618e-07,  6.3840e-08,  1.3380e-07,  1.0000e+00]])

Interesting... It's *almost* the identity matrix. Can that error compound?

In [22]:
random_matrix_2 = torch.rand(2, 2)
random_matrix_2

tensor([[0.4465, 0.0144],
        [0.7484, 0.2023]])

In [23]:
random_matrix_2.inverse() @ random_matrix_2

tensor([[ 1.0000e+00,  2.1931e-09],
        [-9.4038e-08,  1.0000e+00]])

In [24]:
random_matrix_2.inverse() @ random_matrix_2 @ random_matrix_2.inverse() @ random_matrix_2

tensor([[ 1.0000e+00,  5.2082e-09],
        [-4.5090e-07,  1.0000e+00]])

In [25]:
random_matrix_2.inverse() @ random_matrix_2 @ random_matrix_2.inverse() @ random_matrix_2 @ random_matrix_2.inverse() @ random_matrix_2

tensor([[ 1.0000e+00,  8.2234e-09],
        [-4.5090e-07,  1.0000e+00]])

In [26]:
random_matrix_2.inverse() @ random_matrix_2 @ random_matrix_2.inverse() @ random_matrix_2 @ random_matrix_2.inverse() @ random_matrix_2 @ random_matrix_2.inverse() @ random_matrix_2 @ random_matrix_2.inverse() @ random_matrix_2 @ random_matrix_2.inverse() @ random_matrix_2 @ random_matrix_2.inverse() @ random_matrix_2 @ random_matrix_2.inverse() @ random_matrix_2 @ random_matrix_2.inverse() @ random_matrix_2 @ random_matrix_2.inverse() @ random_matrix_2 @ random_matrix_2.inverse() @ random_matrix_2 @ random_matrix_2.inverse() @ random_matrix_2

tensor([[ 1.0000e+00,  1.4254e-08],
        [-4.5090e-07,  1.0000e+00]])

Actually, we didn't check the determinant.

In [27]:
random_matrix_2.det()

tensor(0.0796)

In [28]:
random_matrix_2

tensor([[0.4465, 0.0144],
        [0.7484, 0.2023]])

In [29]:
random_matrix_2 = random_matrix_2 / random_matrix_2.det()

In [30]:
random_matrix_2

tensor([[5.6097, 0.1805],
        [9.4019, 2.5420]])

In [31]:
random_matrix_2.inverse() @ random_matrix_2

tensor([[ 1.0000e+00, -2.0725e-09],
        [ 2.4033e-07,  1.0000e+00]])

Welp. Yeah, low probability the determinant is not $0$ for a random square matrix.