In [1]:
import numpy as np

In [2]:
array_1 = np.array([6,2,7,4,8,3,8,9,4])

In [7]:
np.random.normal(array_1, scale = 1)

array([6.82921008, 2.37949778, 6.41830401, 4.74658378, 9.47325958,
       3.75570712, 7.14548585, 7.80120221, 4.91742842])

In [15]:
np.random.uniform(array_1)

array([1.69460628, 1.45907957, 3.1538941 , 2.95300781, 6.01625932,
       2.4181996 , 4.04994229, 4.93675708, 3.75688328])

In [16]:
np.random.normal(array_1, scale = 1) + np.random.uniform(array_1)

array([10.54642568,  3.07771748, 12.51975674,  7.72953099, 10.49190946,
        3.32595149, 16.55332884, 16.02730747,  7.30173596])